T("global member", function(){ return document.title });
T("global location", function(){ return document.location.href + window.location.href });
T("chain", function(){ return window.window.self.frames.document.location.href });
T("chain derived escape", function(){ function g(x){ return x.location.href } return g(window.document) });
T("alias", function(){ var d = document; d.title; return d.location.href });
T("alias identity", function(){ var d = document; return d === document });
T("alias identity win", function(){ var w = window; return w === self });
T("alias returned", function(){ var d = document; return d });
T("alias thrown", function(){ var d = document; try { throw d } catch (e) { return e.location.href } });
T("alias yielded", function(){ var d = document; function* g(){ yield d } return g().next().value.location.href });
T("alias in array", function(){ var d = document; return [d][0].location.href });
T("alias in object", function(){ var d = document; return ({ x: d }).x.location.href });
T("alias shorthand", function(){ var d = document; return ({ d }).d.location.href });
T("alias spread", function(){ var d = document; return [...[d]][0].location.href });
T("alias spread arg", function(){ var d = document; function g(x){ return x.location.href } return g(...[d]) });
T("alias to field", function(){ var d = document, o = {}; o.d = d; return o.d.location.href });
T("alias to fn", function(){ var d = document; return (function(x){ return x.location.href })(d) });
T("alias to closure", function(){ var d = document; return (function(){ return d.location.href })() });
T("alias arrow expr body", function(){ var d = document; return (() => d)().location.href });
T("alias default param", function(){ return (function(w = window){ return w.location.href })() });
T("alias reassigned other", function(){ var q = document; q = { location: { href: "mine" } }; return q.location.href });
T("alias reassigned loop", function(){ var n = document, out = ""; for (var i = 0; i < 3; i++) { out += n.location.href; n = i ? document : window } return out });
T("alias assign chain", function(){ var a, b; a = b = window; return a.location.href + b.location.href });
T("alias conditional", function(){ var w = typeof window !== "undefined" ? window : {}; return w.location.href });
T("alias logical or", function(){ var w = window.nope || window; return w.location.href });
T("alias logical and", function(){ var w = window && window.document; return w.location.href });
T("alias nullish", function(){ var w = window.nope ?? document; return w.location.href });
T("alias sequence", function(){ var w = (0, window); return w.location.href });
T("alias computed", function(){ var w = window, k = "location"; return w[k].href });
T("alias computed literal", function(){ var w = window; return w["location"].href });
T("alias computed template", function(){ var w = window; return w[`location`].href });
T("alias index", function(){ var w = window; return String(w[0]) });
T("alias compare", function(){ var w = window; return w == PW });
T("alias switch", function(){ var w = window; switch (w) { case PW: return "pw"; default: return "other" } });
T("alias typeof", function(){ var w = window; return typeof w });
T("alias in", function(){ var w = window; return "innerWidth" in w });
T("alias instanceof", function(){ var w = window; return w instanceof Object });
T("alias template", function(){ var d = document; return `${d.title}` });
T("alias delete", function(){ var d = document; d.x = 1; delete d.x; return d.x });
T("alias set", function(){ var d = document; d.title = "new"; return document.title });
T("alias set location", function(){ var d = document; d.location = "/x"; return "set" });
T("global set location", function(){ window.location = "/x"; document.location = "/y"; return "set" });
T("alias compound", function(){ var d = document; d.title += "!"; return document.title });
T("alias update", function(){ var w = window; w.innerWidth++; return window.innerWidth });
T("alias call method", function(){ var d = document; return d.createElement("a").ownerDocument === document });
T("alias method this", function(){ var w = window; var got; w.addEventListener("x", function(){ got = this.location.href }); w.dispatch(); return got });
T("alias optional", function(){ var w = window; return w?.location.href });
T("alias optional chain derived", function(){ var w = window; return w?.document.location.href });
T("alias optional call", function(){ var w = window; return w.open?.().location.href });
T("alias optional derived arg", function(){ var w = window; return (function(x){ return x.location.href })(w?.document) });
T("destructure", function(){ const { document: dd, innerWidth } = window; return dd.location.href + innerWidth });
T("destructure unsafe key", function(){ const { location: l } = window; return l.href });
T("destructure rest", function(){ const { innerWidth, ...rest } = window; return rest.location.href });
T("destructure default", function(){ const { document: dd = 1 } = window; return dd.location.href });
T("destructure assign", function(){ var dd; ({ document: dd } = window); return dd.location.href });
T("iife", function(){ return (function(w, d){ return w.location.href + d.location.href + d.defaultView.location.href })(window, document) });
T("iife call", function(){ return (function(w){ return w.location.href }).call(null, window) });
T("iife arrow", function(){ return ((w) => w.location.href)(window) });
T("iife arguments", function(){ return (function(w){ return arguments[0].location.href })(window) });
T("iife arguments sloppy alias", function(){ return (function(w){ arguments[0] = 1; return w.location.href })(window) });
T("iife spread", function(){ return (function(a, w){ return w.location.href })(...[1, window]) });
T("iife extra", function(){ return (function(){ return arguments[1].location.href })(1, window) });
T("named fn", function(){ function g(w){ return w.location.href } return g(window) + g({ location: { href: "o" } }) });
T("named fn escapes", function(){ function g(w){ return w.location.href } var h = g; return h(window) });
T("named fn reassigned", function(){ function g(w){ return w.location.href } var r = g(window); g = function(w){ return "x" }; return r + g(window) });
T("recursive iife", function(){ return (function f(w, n){ return n ? f(w, n - 1) : w.location.href })(window, 2) });
T("umd", function(){ return (function(root, factory){ return factory(root) })(window, function(C){ var D = C.document; return C.location.href + D.location.href }) });
T("umd factory escapes", function(){ var saved; return (function(root, factory){ saved = factory; return factory(root) })(window, function(C){ return C.location.href }) + saved({ location: { href: "o" } }) });
T("umd factory reassigned", function(){ return (function(root, factory){ factory = function(x){ return x.location.href + "!" }; return factory(root) })(window, function(C){ return C.location.href }) });
T("eval scope", function(){ var d = document; return eval("d").location.href });
T("eval nested", function(){ var d = document; return (function(){ return eval("d.location.href") })() });
T("with", function(){ var o = { d: 1 }; var d = document; with (o) { d = window } return d.location.href });
T("with read", function(){ var w = window; with ({}) { return w.location.href } });
T("with global", function(){ with ({ document: { location: { href: "shadow" } } }) { return document.location.href } });
T("catch param", function(){ try { throw window } catch (w) { return w.location.href } });
T("class field", function(){ class C { w = window; get() { return this.w.location.href } } return new C().get() });
T("class method", function(){ var d = document; class C { m() { return d.location.href } } return new C().m() });
T("getter", function(){ var d = document; var o = { get x() { return d } }; return o.x.location.href });
T("async", function(){ var d = document; var r; (async function(){ r = d.location.href })(); return r });
T("label", function(){ var d = document; l: { break l } return d.location.href });
T("comma member", function(){ var d = document; return (0, d).location.href });
T("paren member", function(){ var d = document; return (d).location.href });
T("new", function(){ var w = window; w.K = function(){ this.v = 1 }; return new w.K().v });
T("for-in", function(){ var d = document, n = 0; for (var k in d) n++; return n > 0 });
T("for-of alias", function(){ var arr = [window, document], out = ""; for (var x of arr) out += x.location.href; return out });
T("for-of head", function(){ var out = ""; for (var w of [window]) out += w.location.href; return out });
T("return global", function(){ return window });
T("escape to obj method", function(){ var o = { f(x){ return x.location.href } }; return o.f(document) });
T("Object.keys", function(){ var d = document; return Object.keys(d).length > 0 });
T("defineProperty", function(){ var w = window; Object.defineProperty(w, "zz", { value: 1, configurable: true }); return window.zz });
T("hoisted var alias", function(){ return g(); function g(){ return d.location.href } var d = document });
T("tdz let", function(){ try { d.title } catch (e) { return "tdz" } let d = document });
T("block scope", function(){ var r; { let d = document; r = d.location.href } return r });
T("shadowed window", function(){ var window = { location: { href: "local" } }; return window.location.href });
T("shadowed document param", function(document){ return document.location.href });
T("global this", function(){ return typeof this });
T("wm window.location", function(){ return window.location.href + document.location.href + window["location"].href });
T("wm top parent", function(){ var w = window; return String(w.top === PW) + String(w.parent === PW) + typeof w.eval });
T("wm eval call", function(){ return window.eval("1") });
T("wm defaultView", function(){ var d = document; return d.defaultView === PW });
T("wm location method", function(){ var d = document; return typeof d.location.toString() });
T("wm optional", function(){ var w = window; return w?.location.href + (w?.location).href });
T("wm assign", function(){ var w = window; w.location = "/z"; return "ok" });
T("wm compound", function(){ var w = window; try { w.location += "q" } catch (e) { return "t" } return "ok" });
T("wm delete", function(){ var w = window; return String(delete w.location) });
T("wm destructure target", function(){ var w = window, o = { a: "/p" }; ({ a: w.location } = o); return "ok" });
T("wm for-in target", function(){ var w = window; for (w.location in { a: 1 }) break; return "ok" });
T("wm location escape", function(){ var w = window; var l = w.location; return l.href });
T("wm in chain", function(){ var w = window; return w.document.location.href + w.document.defaultView.location.href });
T("twin arrow body returns the proxy", function(){ var e = document, O = { title: "o" }; if (Math.random() > 2) e = O; var g = () => e = document; var r = g(); e.title; return r.location.href });
T("twin arrow body in a sequence", function(){ var e = document; if (Math.random() > 2) e = 1; var g = () => (e = document, e); e.title; return g().location.href });
T("recursive named iife", function () { return (function f(w, n) { return n ? f({ title: "other" }, 0) : w.title })(document, 1) });
T("recursive named iife via call", function () { return (function f(w, n) { return n ? f.call(null, { title: "other" }, 0) : w.title }).call(null, document, 1) });
T("named iife escaping", function () { var g; (function f(w) { g = f; return w.title })(document); return g({ title: "other" }) });
T("with shadows a definite local", function () { var w = window; String(w); with ({ w: { innerWidth: 99 } }) { return w.innerWidth } });
T("with shadows a twin", function () { var w = window; if (Math.random() < 2) w = document; String(w); with ({ w: { title: "x" } }) { return w.title } });
T("with leaves an unshadowed local", function () { var w = window; String(w); with ({ other: 1 }) { return w.innerWidth + w.location.href } });
