import { basicTest } from "../../../testcommon.ts";

// Calls that typical site bootstrap / analytics / framework code makes. Each is
// run in isolation and its outcome (ok + small result, or error name) recorded,
// then compared to bare Chrome with assertConsistent. Run WITHOUT RUNWAY_FAST.
const ops: Record<string, string> = {
	matchMedia: `return matchMedia("(min-width: 1px)").matches`,
	intersectionObserver: `const io = new IntersectionObserver(() => {}); io.observe(document.body); io.disconnect(); return true`,
	resizeObserver: `const ro = new ResizeObserver(() => {}); ro.observe(document.body); ro.disconnect(); return true`,
	mutationObserver: `const mo = new MutationObserver(() => {}); mo.observe(document.body, { childList: true, subtree: true, attributes: true }); document.body.appendChild(document.createElement("i")).remove(); const r = mo.takeRecords().length; mo.disconnect(); return r`,
	requestIdleCallback: `return typeof requestIdleCallback(() => {})`,
	rAF: `return await new Promise((r) => requestAnimationFrame((t) => r(typeof t)))`,
	randomUUID: `return crypto.randomUUID().length`,
	getRandomValues: `return crypto.getRandomValues(new Uint8Array(4)).length`,
	subtleDigest: `return (await crypto.subtle.digest("SHA-256", new TextEncoder().encode("x"))).byteLength`,
	structuredClone: `return structuredClone({ a: [1, new Map([[1, 2]])] }).a[1].get(1)`,
	intl: `return new Intl.NumberFormat("en-US").format(1234.5) + new Intl.DateTimeFormat("en-US", { timeZone: "UTC" }).format(0)`,
	permissions: `return (await navigator.permissions.query({ name: "notifications" })).state`,
	notificationPermission: `return Notification.permission`,
	storageEstimate: `const e = await navigator.storage.estimate(); return typeof e.quota`,
	storagePersisted: `return typeof (await navigator.storage.persisted())`,
	fontsReady: `await document.fonts.ready; return document.fonts.status`,
	fontFace: `const f = new FontFace("x", "url(/nofont.woff2)"); document.fonts.add(f); return f.status`,
	cssSupports: `return CSS.supports("display", "grid")`,
	cssEscape: `return CSS.escape("a b")`,
	customElement: `customElements.define("rv0-surf-el", class extends HTMLElement { connectedCallback() { this.textContent = "c"; } }); const e = document.createElement("rv0-surf-el"); document.body.append(e); const t = e.textContent; e.remove(); return t`,
	shadow: `const h = document.createElement("div"); const s = h.attachShadow({ mode: "open" }); s.innerHTML = "<slot></slot><b>x</b>"; return s.querySelector("b").textContent`,
	animate: `const d = document.createElement("div"); document.body.append(d); const a = d.animate([{ opacity: 0 }, { opacity: 1 }], 10); await a.finished; d.remove(); return a.playState`,
	perfMarkMeasure: `performance.mark("rv0a"); performance.mark("rv0b"); return performance.measure("rv0m", "rv0a", "rv0b").name`,
	perfNow: `return typeof performance.now()`,
	perfNavTiming: `const n = performance.getEntriesByType("navigation")[0]; return n ? n.entryType + ":" + (n.name === location.href) : "none"`,
	perfTimeOrigin: `return typeof performance.timeOrigin`,
	perfObserver: `const po = new PerformanceObserver(() => {}); po.observe({ type: "mark", buffered: true }); po.disconnect(); return PerformanceObserver.supportedEntryTypes.includes("mark")`,
	perfToJSON: `return typeof performance.toJSON().timeOrigin`,
	idbOpen: `return await new Promise((res, rej) => { const r = indexedDB.open("rv0surf", 1); r.onupgradeneeded = () => r.result.createObjectStore("s"); r.onsuccess = () => { const db = r.result; const tx = db.transaction("s", "readwrite"); tx.objectStore("s").put(1, "k"); tx.oncomplete = () => { db.close(); res("ok"); }; }; r.onerror = () => rej(r.error); })`,
	idbDatabases: `return Array.isArray(await indexedDB.databases())`,
	cachesOpen: `const c = await caches.open("rv0surf"); await c.put("/rv0surf", new Response("x")); const m = await c.match("/rv0surf"); await caches.delete("rv0surf"); return await m.text()`,
	broadcastChannel: `const b = new BroadcastChannel("rv0"); b.postMessage(1); b.close(); return true`,
	messageChannel: `const mc = new MessageChannel(); const p = new Promise((r) => (mc.port2.onmessage = (e) => r(e.data))); mc.port1.postMessage(5); return await p`,
	offscreenCanvas: `const c = new OffscreenCanvas(4, 4); return !!c.getContext("2d")`,
	webgl: `return !!document.createElement("canvas").getContext("webgl")`,
	canvasToDataURL: `const c = document.createElement("canvas"); c.width = c.height = 2; return c.toDataURL().slice(0, 22)`,
	createImageBitmap: `const b = await createImageBitmap(new ImageData(1, 1)); return b.width`,
	audioContext: `const a = new (window.AudioContext || window.webkitAudioContext)(); const s = a.state; a.close(); return typeof s`,
	mediaSource: `return MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E"')`,
	mediaDevices: `return typeof navigator.mediaDevices.enumerateDevices`,
	connection: `return typeof navigator.connection`,
	userAgentData: `return typeof navigator.userAgentData?.brands`,
	uaHighEntropy: `const v = await navigator.userAgentData.getHighEntropyValues(["platform"]); return typeof v.platform`,
	languages: `return navigator.languages.length > 0`,
	cookieEnabled: `return navigator.cookieEnabled`,
	onLine: `return navigator.onLine`,
	hardwareConcurrency: `return typeof navigator.hardwareConcurrency`,
	serviceWorkerContainer: `return typeof navigator.serviceWorker`,
	swGetRegistrations: `return Array.isArray(await navigator.serviceWorker.getRegistrations())`,
	clipboardType: `return typeof navigator.clipboard.writeText`,
	locks: `return await navigator.locks.request("rv0", async () => "held")`,
	sendBeacon: `return navigator.sendBeacon("/beacon", "x")`,
	visibility: `return document.visibilityState + ":" + document.hidden`,
	hasFocus: `return typeof document.hasFocus()`,
	selection: `return typeof getSelection().toString()`,
	range: `const r = document.createRange(); r.selectNodeContents(document.body); return typeof r.getBoundingClientRect().width`,
	elementFromPoint: `return document.elementFromPoint(1, 1) !== undefined`,
	scrollTo: `scrollTo(0, 0); scrollBy({ top: 0 }); return scrollY`,
	gbcr: `return typeof document.body.getBoundingClientRect().top`,
	computedStyle: `return getComputedStyle(document.body).display`,
	execCommand: `return typeof document.execCommand("copy")`,
	textEncoderDecoder: `return new TextDecoder().decode(new TextEncoder().encode("é"))`,
	compressionStream: `const s = new Blob(["hi"]).stream().pipeThrough(new CompressionStream("gzip")); return (await new Response(s).arrayBuffer()).byteLength > 0`,
	objectURL: `const u = URL.createObjectURL(new Blob(["x"])); const t = await (await fetch(u)).text(); URL.revokeObjectURL(u); return t + ":" + u.startsWith("blob:" + location.origin)`,
	imageDecode: `const i = new Image(); i.src = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"; await i.decode(); return i.naturalWidth`,
	historyScrollRestoration: `history.scrollRestoration = "manual"; const v = history.scrollRestoration; history.scrollRestoration = "auto"; return v`,
	historyLength: `return typeof history.length`,
	historyState: `history.replaceState({ a: 1 }, ""); return history.state.a`,
	pushStateHash: `const h = location.href; history.pushState(null, "", "#rv0"); const r = location.hash; history.replaceState(null, "", h); return r`,
	locationParts: `return [location.protocol, location.host === location.hostname + (location.port ? ":" + location.port : ""), location.origin === new URL(location.href).origin].join(",")`,
	documentDomain: `return document.domain === location.hostname`,
	documentReferrer: `return typeof document.referrer`,
	documentCookieRoundtrip: `document.cookie = "rv0surf=1; path=/"; const r = document.cookie.includes("rv0surf=1"); document.cookie = "rv0surf=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/"; return r`,
	localStorageRoundtrip: `localStorage.setItem("rv0s", "1"); const r = localStorage.getItem("rv0s") + ":" + ("rv0s" in localStorage) + ":" + Object.keys(localStorage).includes("rv0s"); localStorage.removeItem("rv0s"); return r`,
	sessionStorageJSON: `sessionStorage.setItem("rv0j", JSON.stringify({ a: 1 })); const r = JSON.parse(sessionStorage.getItem("rv0j")).a; sessionStorage.clear(); return r`,
	workerInline: `const w = new Worker(URL.createObjectURL(new Blob(["onmessage = (e) => postMessage(e.data * 2)"], { type: "text/javascript" }))); const r = await new Promise((res) => { w.onmessage = (e) => res(e.data); w.postMessage(21); }); w.terminate(); return r`,
	wasm: `const m = await WebAssembly.instantiate(new Uint8Array([0,97,115,109,1,0,0,0])); return typeof m.instance`,
	dynamicImportData: `const m = await import("data:text/javascript,export default 42"); return m.default`,
	fetchJSONHeaders: `const r = await fetch("/", { headers: { "X-Test": "1", "Content-Type": "application/json" } }); return r.status + ":" + typeof r.headers.get("content-type")`,
	xhrBasic: `return await new Promise((res) => { const x = new XMLHttpRequest(); x.open("GET", "/"); x.onload = () => res(x.status + ":" + (x.responseURL === location.href.split("#")[0] || x.responseURL === new URL("/", location.href).href)); x.send(); })`,
	eventTargetSubclass: `class T extends EventTarget {}; const t = new T(); let n = 0; t.addEventListener("x", () => n++); t.dispatchEvent(new Event("x")); return n`,
	customEvent: `let d; addEventListener("rv0ce", (e) => (d = e.detail), { once: true }); dispatchEvent(new CustomEvent("rv0ce", { detail: 7 })); return d`,
	abortSignalTimeout: `return typeof AbortSignal.timeout(1000).aborted`,
	queueMicrotask: `return await new Promise((r) => queueMicrotask(() => r(1)))`,
	setTimeoutArgs: `return await new Promise((r) => setTimeout((a, b) => r(a + b), 0, 1, 2))`,
	setIntervalId: `const id = setInterval(() => {}, 1000); clearInterval(id); return typeof id`,
	errorStackString: `return typeof new Error("x").stack`,
	functionToStringNative: `return Function.prototype.toString.call(fetch).includes("[native code]") + ":" + Function.prototype.toString.call(document.createElement).includes("[native code]")`,
	getterToStringNative: `return Function.prototype.toString.call(Object.getOwnPropertyDescriptor(Document.prototype, "cookie").get).includes("[native code]")`,
	windowProps: `return ["top", "parent", "self", "frames", "opener", "length", "name", "closed"].map((k) => typeof window[k]).join(",")`,
	windowOpenTypeof: `return typeof window.open`,
	postMessageSelf: `return await new Promise((r) => { addEventListener("message", (e) => r(e.origin === location.origin && e.source === window), { once: true }); postMessage("x", "*"); })`,
	trustedTypes: `return typeof trustedTypes?.createPolicy`,
	reportingObserver: `return typeof ReportingObserver`,
	navigationAPI: `return typeof navigation?.currentEntry?.url === "string" ? (navigation.currentEntry.url === location.href) : "none"`,
	jsonScriptRead: `const s = document.createElement("script"); s.type = "application/json"; s.textContent = '{"a":1}'; document.body.append(s); const v = JSON.parse(s.textContent).a; s.remove(); return v`,
	inlineScriptExec: `window.__rv0exec = 0; const s = document.createElement("script"); s.textContent = "window.__rv0exec = 1"; document.body.append(s); return window.__rv0exec`,
	scriptSrcLoad: `return await new Promise((r) => { const s = document.createElement("script"); s.src = "data:text/javascript,window.__rv0src=1"; s.onload = () => r(window.__rv0src); s.onerror = () => r("error"); document.head.append(s); })`,
	linkStylesheetLoad: `return await new Promise((r) => { const l = document.createElement("link"); l.rel = "stylesheet"; l.href = "data:text/css,.rv0x{color:red}"; l.onload = () => r("load"); l.onerror = () => r("error"); document.head.append(l); })`,
	imgLoadRelative: `return await new Promise((r) => { const i = new Image(); i.onload = () => r("load"); i.onerror = () => r("error"); i.src = "/nonexistent.png"; })`,
	iframeAboutBlank: `const f = document.createElement("iframe"); document.body.append(f); const d = f.contentDocument; d.open(); d.write("<p id=x>hi</p>"); d.close(); const t = d.getElementById("x").textContent + ":" + (f.contentWindow.parent === window); f.remove(); return t`,
	iframeSrcdoc: `return await new Promise((r) => { const f = document.createElement("iframe"); f.srcdoc = "<p id=x>s</p><script>parent.postMessage('srcdoc-ok','*')<\\/script>"; addEventListener("message", function h(e) { if (e.data === "srcdoc-ok") { removeEventListener("message", h); r(f.contentDocument.getElementById("x").textContent); f.remove(); } }); document.body.append(f); })`,
	documentWriteClosed: `return typeof document.write`,
	domParser: `const d = new DOMParser().parseFromString("<a href='/x'>t</a>", "text/html"); return d.querySelector("a").getAttribute("href")`,
	domParserXML: `const d = new DOMParser().parseFromString("<?xml version='1.0'?><r><c a='1'/></r>", "application/xml"); return d.documentElement.nodeName + ":" + !!d.querySelector("parsererror")`,
	xmlSerializer: `return new XMLSerializer().serializeToString(new DOMParser().parseFromString("<r><c/></r>", "application/xml"))`,
	insertAdjacentHTML: `const d = document.createElement("div"); d.insertAdjacentHTML("beforeend", "<a href='/y'>y</a>"); return d.firstChild.getAttribute("href")`,
	templateContent: `const t = document.createElement("template"); t.innerHTML = "<img src='/t.png'>"; return t.content.firstChild.getAttribute("src")`,
	cloneImport: `const t = document.createElement("template"); t.innerHTML = "<a href='/c'>c</a>"; return document.importNode(t.content, true).firstChild.getAttribute("href")`,
	anchorProps: `const a = document.createElement("a"); a.href = "/p/q?x=1#h"; return [a.pathname, a.search, a.hash, a.host === location.host, a.origin === location.origin].join(",")`,
	formAction: `const f = document.createElement("form"); f.action = "/submit"; return new URL(f.action).pathname + ":" + (new URL(f.action).origin === location.origin)`,
	baseURI: `return document.baseURI === location.href.split("#")[0] || document.baseURI === location.href`,
	currentScript: `return document.currentScript === null ? "null" : document.currentScript.tagName`,
};

export default [
	basicTest({
		name: "rv0-surface",
		js: `
			const out = {};
			const names = ${JSON.stringify(Object.keys(ops))};
			const fns = [${Object.values(ops)
				.map((b) => `async () => { ${b} }`)
				.join(",\n")}];
			for (let i = 0; i < names.length; i++) {
				try {
					const v = await Promise.race([fns[i](), new Promise((_, rej) => setTimeout(() => rej(new Error("timeout")), 4000))]);
					out[names[i]] = "ok:" + String(v).slice(0, 80);
				} catch (e) {
					out[names[i]] = "err:" + (e && e.name) + ":" + String(e && e.message).slice(0, 80);
				}
			}
			assertConsistent("surface", out);
			window.__rv0surface = out;
		`,
	}),
];
