use std::{error::Error, str::FromStr};

use oxc::allocator::StringBuilder;
use thiserror::Error as ThisError;

pub trait UrlRewriter {
	fn rewrite(
		&self,
		cfg: &Config,
		flags: &Flags,
		url: &str,
		builder: &mut StringBuilder,
		module: bool,
	) -> Result<(), Box<dyn Error + Sync + Send>>;
}

pub struct Config {
	pub prefix: String,

	pub wrapfn: String,
	pub wrappropertybase: String,
	pub wrappropertyfn: String,
	pub callfn: String,
	pub cleanrestfn: String,
	pub importfn: String,
	pub rewritefn: String,
	pub metafn: String,
	pub pushsourcemapfn: String,
	pub registerrealmfn: String,

	pub trysetfn: String,
	pub templocid: String,
	pub tempreceiverid: String,
	pub tempcalleeid: String,
	pub tempunusedid: String,

	/// `ppsc`: the real object behind one of the global or document proxies
	pub unwrapfn: String,
	/// `ppsc`: what a local's name is followed by to name its twin, the local that holds the
	/// real object where the local itself holds the proxy
	pub realsuffix: String,
	/// `ppsc` with `ppsc_wrap_this`: a function's `this`, wrapped once where it is used unsafely
	pub tempthisid: String,
	/// `ppsc` with `ppsc_wrap_this`: the real window and document, constants a `this` is compared
	/// against before it is wrapped
	pub rawwindowid: String,
	pub rawdocumentid: String,
}

/// Which rewrite a script gets. The mirror of `JsRewriter` in `types.ts`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum JsRewriter {
	/// rewrites the key of every member access that could name something unsafe, answered by
	/// accessors on `Object.prototype`
	Dpsc,
	/// rewrites only the references to the globals, handing back a `Proxy` for the window and the
	/// document - except where every use of one is a use the proxy would answer the same
	Ppsc,
	/// `ppsc`, with a static read of an unsafe name - `.location`, `.top` - renamed to `dpsc`'s
	/// accessor for it, so that it needs no proxy either
	#[default]
	PpscHybrid,
}

#[derive(Debug, ThisError)]
#[error("not a js rewriter: {0}")]
pub struct InvalidJsRewriter(String);

impl FromStr for JsRewriter {
	type Err = InvalidJsRewriter;

	fn from_str(s: &str) -> Result<Self, Self::Err> {
		match s {
			"dpsc" => Ok(Self::Dpsc),
			"ppsc" => Ok(Self::Ppsc),
			"ppsc-hybrid" => Ok(Self::PpscHybrid),
			_ => Err(InvalidJsRewriter(s.to_string())),
		}
	}
}

/// How a stack frame is traced back to the script that owns it, which is what
/// lets an incumbent settings object be identified. The mirror of
/// `IncumbencyMode` in `types.ts`, and what arrives here is the configured
/// mode already downgraded to what the engine can actually do.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum IncumbencyMode {
	/// `Error.prepareStackTrace` plus `CallSite.getScriptHash`, both V8 only
	Pst,
	/// not implemented yet; acts as `None`
	Stamp,
	/// not implemented yet; acts as `None`
	LazyStamp,
	/// no attribution
	#[default]
	None,
}

#[derive(Debug, ThisError)]
#[error("not an incumbency mode: {0}")]
pub struct InvalidIncumbencyMode(String);

impl FromStr for IncumbencyMode {
	type Err = InvalidIncumbencyMode;

	fn from_str(s: &str) -> Result<Self, Self::Err> {
		match s {
			"pst" => Ok(Self::Pst),
			"stamp" => Ok(Self::Stamp),
			"lazystamp" => Ok(Self::LazyStamp),
			"none" => Ok(Self::None),
			_ => Err(InvalidIncumbencyMode(s.to_string())),
		}
	}
}

#[derive(Debug)]
pub struct Flags {
	pub base: String,
	pub sourcetag: String,
	/// the private ID a `pst` script registers itself under, fresh per
	/// rewrite. Generated by the caller, not here
	pub script_id: String,

	pub is_module: bool,
	pub capture_errors: bool,
	pub do_sourcemaps: bool,
	/// whether the sourcemap has to be handed over by the script itself, from
	/// its prelude, rather than by the caller - which it cannot be when the
	/// consumer lives in another realm
	pub inline_sourcemap: bool,
	pub disable_computed_wrap: bool,
	pub destructure_rewrites: bool,

	pub incumbency: IncumbencyMode,
	pub js_rewriter: JsRewriter,
	/// `ppsc` only: follow a function's `this` too, and wrap it where it is used unsafely. Off, a
	/// `this` is left as it always has been - which is the window whenever a sloppy function is
	/// called bare, and whenever an unwrapped window is a method's receiver
	pub ppsc_wrap_this: bool,
}
