import { probeTest } from "./lib.ts";

const mk = `const a=document.createElement('a'); a.setAttribute('href','/x?y=1'); a.setAttribute('data-k','v'); document.body.appendChild(a);`;
const probes: Record<string, string> = {
	nodeValue: `${mk} const n=a.getAttributeNode('href'); return [n.value, n.nodeValue, n.textContent];`,
	attrs_named_nodeValue: `${mk} return [a.attributes.href.nodeValue, a.attributes.href.value, a.attributes.length, a.attributes[0].name, a.attributes[0].nodeName];`,
	attr_set_nodeValue: `${mk} a.getAttributeNode('href').nodeValue='/z'; return [a.getAttribute('href'), a.href.replace(/localhost:\\d+/,'L')];`,
	attr_set_textContent: `${mk} a.getAttributeNode('href').textContent='/t'; return [a.getAttribute('href'), a.href.replace(/localhost:\\d+/,'L')];`,
	attr_clone: `${mk} const c=a.getAttributeNode('href').cloneNode(); return [c.value, c.nodeValue, c.name];`,
	attr_isEqualNode: `${mk} const b=document.createElement('a'); b.setAttribute('href','/x?y=1'); b.setAttribute('data-k','v'); return [a.isEqualNode(b), a.getAttributeNode('href').isEqualNode(b.getAttributeNode('href'))];`,
	el_clone_equal: `${mk} const c=a.cloneNode(true); return [a.isEqualNode(c), c.getAttribute('href'), c.attributes.length];`,
	iter_attrs: `${mk} return Array.from(a.attributes).map(x=>x.name+'='+x.value);`,
	iter_forof: `${mk} const out=[]; for (const x of a.attributes) out.push(x.nodeName+'='+x.nodeValue); return out;`,
	slice_call: `${mk} return Array.prototype.slice.call(a.attributes).map(x=>x.name);`,
	attrs_instanceof: `${mk} return [a.attributes instanceof NamedNodeMap, a.attributes === a.attributes, Object.prototype.toString.call(a.attributes)];`,
	attrs_live: `${mk} const m=a.attributes; a.setAttribute('title','t'); a.removeAttribute('data-k'); return [m.length, Array.from(m).map(x=>x.name)];`,
	img_attrs: `const i=document.createElement('img'); i.src='/i.png'; i.srcset='/i1.png 1x, /i2.png 2x'; return [i.attributes.length, Array.from(i.attributes).map(x=>x.name+'='+x.value), i.outerHTML];`,
	lookupNamespace: `${mk} return [a.hasAttribute('scramjet-attr-href'), a.getAttribute('scramjet-attr-href'), a.matches('[scramjet-attr-href]')];`,
	dataset: `${mk} return [a.dataset.k, JSON.stringify(Object.keys(a.dataset))];`,
	compareDocPos: `${mk} const x=a.getAttributeNode('href'), y=a.getAttributeNode('data-k'); return x.compareDocumentPosition(y);`,
	mutation_attr: `${mk} const recs=[]; const mo=new MutationObserver(l=>l.forEach(r=>recs.push(r.attributeName+':'+r.oldValue))); mo.observe(a,{attributes:true, attributeOldValue:true}); a.setAttribute('href','/n'); a.href='/m'; a.removeAttribute('href'); await new Promise(r=>setTimeout(r,10)); return recs;`,
	form_action_empty: `const f=document.createElement('form'); return [f.action.replace(/localhost:\\d+/,'L'), f.getAttribute('action')];`,
	form_action_set: `const f=document.createElement('form'); f.action='submit?x'; return [f.action.replace(/localhost:\\d+/,'L'), f.getAttribute('action')];`,
	button_formaction_empty: `const f=document.createElement('button'); return [f.formAction.replace(/localhost:\\d+/,'L')];`,
	a_parts: `${mk} return [a.protocol, a.host.replace(/\\d+/,'P'), a.pathname, a.search, a.hash, a.origin.replace(/\\d+$/,'P')];`,
	a_parts_set: `${mk} a.pathname='/p2'; a.search='?q=2'; a.hash='h'; return [a.getAttribute('href'), a.href.replace(/localhost:\\d+/,'L')];`,
	a_host_set: `${mk} a.host='other.example'; return [a.getAttribute('href'), a.href];`,
	a_toString: `${mk} return [String(a).replace(/localhost:\\d+/,'L'), a+'' === a.href];`,
	area_href: `const ar=document.createElement('area'); ar.href='/ar'; return [ar.href.replace(/localhost:\\d+/,'L'), ar.pathname];`,
	a_javascript: `const a=document.createElement('a'); a.href='javascript:void(0)'; return [a.href, a.getAttribute('href'), a.protocol];`,
	a_mailto: `const a=document.createElement('a'); a.href='mailto:x@y.z'; return [a.href, a.protocol, a.pathname];`,
	a_tel: `const a=document.createElement('a'); a.href='tel:+123'; return [a.href, a.protocol];`,
	a_empty: `const a=document.createElement('a'); a.href=''; return [a.href.replace(/localhost:\\d+/,'L'), a.getAttribute('href')];`,
	a_hash_only: `const a=document.createElement('a'); a.href='#top'; return [a.href.replace(/localhost:\\d+/,'L'), a.hash, a.pathname];`,
	a_no_href: `const a=document.createElement('a'); return [a.href, a.pathname, a.host, a.origin];`,
	link_href: `const l=document.createElement('link'); l.href='/l.css'; l.rel='preload'; return [l.href.replace(/localhost:\\d+/,'L'), l.getAttribute('href')];`,
	script_src_read: `const s=document.createElement('script'); s.src='/s.js?a=1#h'; return [s.src.replace(/localhost:\\d+/,'L'), s.getAttribute('src')];`,
	iframe_src_read: `const f=document.createElement('iframe'); f.src='/f.html'; return [f.src.replace(/localhost:\\d+/,'L'), f.getAttribute('src')];`,
	video_poster: `const v=document.createElement('video'); v.poster='/p.jpg'; return [v.poster.replace(/localhost:\\d+/,'L'), v.getAttribute('poster')];`,
	object_data: `const o=document.createElement('object'); o.data='/o.swf'; return [o.data.replace(/localhost:\\d+/,'L'), o.getAttribute('data')];`,
	input_src: `const i=document.createElement('input'); i.type='image'; i.src='/in.png'; return [i.src.replace(/localhost:\\d+/,'L')];`,
	blockquote_cite: `const q=document.createElement('blockquote'); q.cite='/c'; return [q.cite.replace(/localhost:\\d+/,'L')];`,
	base_href_read: `const b=document.createElement('base'); b.href='/b/'; return [b.href.replace(/localhost:\\d+/,'L'), b.getAttribute('href')];`,
	meta_content_prop: `const m=document.createElement('meta'); m.name='csrf'; m.content='tok1'; return [m.content, m.getAttribute('content')];`,
	svg_a_href: `const a=document.createElementNS('http://www.w3.org/2000/svg','a'); a.setAttribute('href','/sa'); return [a.href.baseVal, a.getAttribute('href')];`,
	a_download: `const a=document.createElement('a'); a.href='/file.pdf'; a.download='f.pdf'; return [a.download, a.getAttribute('download')];`,
	a_ping: `const a=document.createElement('a'); a.ping='/ping'; return [a.ping, a.getAttribute('ping')];`,
	a_rel: `const a=document.createElement('a'); a.relList.add('noopener'); return [a.rel, a.relList.contains('noopener')];`,
	img_currentSrc: `const i=new Image(); i.src='/cur.png'; await new Promise(r=>{i.onload=i.onerror=r}); return [i.currentSrc.replace(/localhost:\\d+/,'L'), i.complete];`,
	img_srcset_read: `const i=document.createElement('img'); i.srcset='a.png 1x, /b.png 2x'; return [i.srcset, i.getAttribute('srcset')];`,
	source_srcset: `const s=document.createElement('source'); s.srcset='/s1.webp 1x'; s.type='image/webp'; return [s.srcset, s.getAttribute('srcset')];`,
	iframe_srcdoc_read: `const f=document.createElement('iframe'); f.srcdoc='<p>hi <a href="/x">x</a></p>'; return [f.srcdoc, f.getAttribute('srcdoc')];`,
	style_attr_bg: `const d=document.createElement('div'); d.style.backgroundImage='url(/bg.png)'; return [d.getAttribute('style'), d.style.backgroundImage.replace(/localhost:\\d+/,'L')];`,
	toggle_attr: `const d=document.createElement('div'); d.toggleAttribute('hidden'); const r1=d.hidden; d.toggleAttribute('hidden'); return [r1, d.hidden, d.getAttributeNames()];`,
	onclick_attr: `const d=document.createElement('div'); d.setAttribute('onclick','window.__oc=location.host'); document.body.appendChild(d); d.click(); return [window.__oc===location.host, d.getAttribute('onclick')];`,
	onclick_prop_null: `const d=document.createElement('div'); d.setAttribute('onclick','return 1'); d.onclick=null; return [d.getAttribute('onclick'), d.onclick];`,
	removeAttribute_href: `${mk} a.removeAttribute('href'); return [a.hasAttribute('href'), a.href, a.getAttributeNames()];`,
	setAttributeNS_null: `const d=document.createElement('a'); d.setAttributeNS(null,'href','/ns'); return [d.getAttribute('href'), d.href.replace(/localhost:\\d+/,'L'), d.getAttributeNames()];`,
	uppercase_attr: `const d=document.createElement('a'); d.setAttribute('HREF','/up'); return [d.getAttribute('href'), d.getAttribute('HREF'), d.href.replace(/localhost:\\d+/,'L'), d.getAttributeNames()];`,
};

export default [
	probeTest({
		name: "rv10-attrs",
		probes,
	}),
];
