import { probeTest } from "./lib.ts";

const probes: Record<string, string> = {
	dup_listener: `let n=0; const f=()=>n++; const t=new EventTarget(); t.addEventListener('x',f); t.addEventListener('x',f); t.dispatchEvent(new Event('x')); return n;`,
	handleEvent_msg: `return await new Promise(r=>{ const o={handleEvent(e){ window.removeEventListener('message', o); r([typeof e.data, JSON.stringify(e.data), e.origin===location.origin, e.source===window, this===o]); }}; window.addEventListener('message', o); postMessage({a:1}, '*'); });`,
	onmessage_prop_roundtrip: `const f=function(){}; window.onmessage=f; const a=window.onmessage===f; const b=document.body.onmessage===f; window.onmessage=null; return [a,b,window.onmessage];`,
	body_onmessage_set: `return await new Promise(r=>{ const f=(e)=>{ document.body.onmessage=null; r([JSON.stringify(e.data), window.onmessage===null]); }; document.body.onmessage=f; postMessage('b', '*'); });`,
	msg_single_arg: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r([e.data, e.origin===location.origin]); }; addEventListener('message', f); postMessage('solo'); });`,
	msg_origin_arg: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r(e.data); }; addEventListener('message', f); postMessage('o1', location.origin); setTimeout(()=>r('DROPPED'),500); });`,
	msg_href_arg: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r(e.data); }; addEventListener('message', f); postMessage('o2', location.href); setTimeout(()=>r('DROPPED'),500); });`,
	msg_wrong_origin: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r(e.data); }; addEventListener('message', f); postMessage('o3', 'https://nope.example'); setTimeout(()=>{removeEventListener('message', f); r('DROPPED')},300); });`,
	msg_opts_dict: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r(e.data); }; addEventListener('message', f); postMessage('o4', {targetOrigin:'*'}); setTimeout(()=>r('DROPPED'),500); });`,
	msg_transfer_port: `return await new Promise(r=>{ const mc=new MessageChannel(); const f=(e)=>{ removeEventListener('message', f); const p=e.ports[0]; p.onmessage=(ev)=>r([e.data, ev.data, e.ports.length]); mc.port2.postMessage({z:2}); }; addEventListener('message', f); postMessage('withport', '*', [mc.port1]); });`,
	msg_iframe_parent: `const f=document.createElement('iframe'); f.srcdoc='<script>parent.postMessage({from:"child", o: location.origin}, "*")<\\/script>'; const p=new Promise(r=>{ const h=(e)=>{ if(e.data&&e.data.from){ removeEventListener('message',h); r([JSON.stringify(e.data), e.origin===location.origin, e.source===f.contentWindow]); } }; addEventListener('message',h); }); document.body.appendChild(f); return await p;`,
	msg_to_iframe: `const f=document.createElement('iframe'); document.body.appendChild(f); const w=f.contentWindow; const p=new Promise(r=>{ w.addEventListener('message', e=>r([JSON.stringify(e.data), e.origin===location.origin, e.source===window])); }); w.postMessage({hi:1}, '*'); return await p;`,
	msg_event_window_event: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r([window.event===e, JSON.stringify(window.event && window.event.data)]); }; addEventListener('message', f); postMessage('we', '*'); });`,
	msg_composedPath: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r([e.composedPath().length, e.currentTarget===window, e.target===window, e instanceof MessageEvent, e.type, typeof e.stopPropagation]); }; addEventListener('message', f); postMessage('cp', '*'); });`,
	msg_once: `let n=0; return await new Promise(r=>{ addEventListener('message', ()=>n++, {once:true}); postMessage('1','*'); postMessage('2','*'); setTimeout(()=>r(n),200); });`,
	msg_signal: `let n=0; const ac=new AbortController(); addEventListener('message', ()=>n++, {signal:ac.signal}); ac.abort(); postMessage('s','*'); await new Promise(r=>setTimeout(r,100)); return n;`,
	msg_capture_remove: `let n=0; const f=()=>n++; addEventListener('message', f, true); removeEventListener('message', f, {capture:true}); postMessage('c','*'); await new Promise(r=>setTimeout(r,100)); return n;`,
	msg_remove_wrong_capture: `let n=0; const f=()=>n++; addEventListener('message', f, true); removeEventListener('message', f); postMessage('c','*'); await new Promise(r=>setTimeout(r,100)); removeEventListener('message', f, true); return n;`,
	msg_data_has_scramjet_keys: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r(Object.keys(e.data)); }; addEventListener('message', f); postMessage({$scramjet$data:1, x:2}, '*'); });`,
	msg_json_string: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r([typeof e.data, e.data]); }; addEventListener('message', f); postMessage(JSON.stringify({a:1}), '*'); });`,
	msg_structured_err: `try { postMessage(()=>{}, '*'); return 'nothrow'; } catch(e) { return e.name; }`,
	msg_ev_lastEventId: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r([e.lastEventId, e.ports.length, Array.isArray(e.ports)]); }; addEventListener('message', f); postMessage('le', '*'); });`,
	msg_initMessageEvent: `const e=document.createEvent('MessageEvent'); e.initMessageEvent('message', false, false, 'd', 'o', '', null); return [e.data, e.origin];`,
	synthetic_msg: `return await new Promise(r=>{ const f=(e)=>{ removeEventListener('message', f); r([e.data, e.origin, e.isTrusted]); }; addEventListener('message', f); dispatchEvent(new MessageEvent('message', {data:'syn', origin:'https://x.example'})); });`,
	worker_msg: `const w=new Worker(URL.createObjectURL(new Blob(['onmessage=e=>postMessage([e.data, e.origin, typeof self.origin])'],{type:'text/javascript'}))); return await new Promise(r=>{ w.onmessage=e=>r([JSON.stringify(e.data), e.origin]); w.postMessage('w'); });`,
	worker_msg_listener: `const w=new Worker(URL.createObjectURL(new Blob(['addEventListener("message", e=>postMessage({got:e.data}))'],{type:'text/javascript'}))); return await new Promise(r=>{ w.addEventListener('message', e=>r(JSON.stringify(e.data))); w.postMessage({x:1}); });`,
	bc_same: `const a=new BroadcastChannel('ch'); const b=new BroadcastChannel('ch'); const p=new Promise(r=>{ b.onmessage=e=>r([JSON.stringify(e.data), e.origin===location.origin, b.name]); }); a.postMessage({m:1}); return await p;`,
	bc_iframe: `const f=document.createElement('iframe'); f.srcdoc='<script>const c=new BroadcastChannel("ch2"); c.postMessage("fromframe")<\\/script>'; const b=new BroadcastChannel('ch2'); const p=new Promise(r=>{ b.onmessage=e=>r(e.data); setTimeout(()=>r('NONE'),1500); }); document.body.appendChild(f); return await p;`,
	bc_worker: `const b=new BroadcastChannel('ch3'); const p=new Promise(r=>{ b.onmessage=e=>r(e.data); setTimeout(()=>r('NONE'),2000); }); new Worker(URL.createObjectURL(new Blob(['new BroadcastChannel("ch3").postMessage("fromworker")'],{type:'text/javascript'}))); return await p;`,
	hashchange: `return await new Promise(r=>{ addEventListener('hashchange', e=>r([e.newURL.includes('#hc'), e.oldURL.includes('/~/'), e.newURL.includes('/~/')]), {once:true}); location.hash='hc'; });`,
	storage_event_iframe: `const f=document.createElement('iframe'); f.src='/deep/dir/other.html'; document.body.appendChild(f); await new Promise(r=>f.onload=r); const p=new Promise(r=>{ addEventListener('storage', e=>r([e.key, e.newValue, e.url.includes('/~/')]), {once:true}); setTimeout(()=>r('NONE'),1500); }); f.contentWindow.localStorage.setItem('sk','sv'); return await p;`,
	settimeout_string: `window.__st=0; setTimeout('window.__st=location.host.length', 0); await new Promise(r=>setTimeout(r,50)); return window.__st===location.host.length;`,
	settimeout_unbound: `const {setTimeout: st} = window; return await new Promise(r=>st(()=>r('ok'),0));`,
	settimeout_call_null: `return await new Promise(r=>setTimeout.call(null, ()=>r('ok'),0));`,
	settimeout_args: `return await new Promise(r=>setTimeout((a,b)=>r([a,b]),0,1,'2'));`,
	settimeout_ret: `const id=setTimeout(()=>{},0); clearTimeout(id); return typeof id;`,
	settimeout_call_obj: `try { setTimeout.call({}, ()=>{}, 0); return 'nothrow'; } catch(e){ return e.name; }`,
	setinterval: `let n=0; return await new Promise(r=>{ const id=setInterval(()=>{ if(++n===3){ clearInterval(id); r(n);} },1); });`,
	settimeout_meta: `return [setTimeout.name, setTimeout.length, String(setTimeout).includes('native code'), Object.getOwnPropertyDescriptor(window,'setTimeout') ? Object.keys(Object.getOwnPropertyDescriptor(window,'setTimeout')).join() : 'none'];`,
	settimeout_iframe: `const f=document.createElement('iframe'); document.body.appendChild(f); return await new Promise(r=>f.contentWindow.setTimeout(()=>r('ok'),0));`,
	settimeout_bigtimeout: `const id=setTimeout(()=>{window.__big=1},2**31); await new Promise(r=>setTimeout(r,30)); clearTimeout(id); return window.__big||0;`,
	settimeout_obj_handler: `window.__oh=0; setTimeout({toString(){return 'window.__oh=5'}}, 0); await new Promise(r=>setTimeout(r,30)); return window.__oh;`,
	queueMicrotask: `return await new Promise(r=>queueMicrotask(()=>r('ok')));`,
	requestIdle: `return await new Promise(r=>requestIdleCallback(()=>r('ok')));`,
};

export default [
	probeTest({
		name: "rv10-events",
		probes,
	}),
];
