T("this listener real", function(){ var got; var w = window; w.addEventListener("x", function(){ got = this.location.href }); w.dispatchReal(); return got });
T("this listener proxy", function(){ var got; var w = window; w.addEventListener("x", function(){ got = this.location.href }); w.dispatch(); return got });
T("this method elided", function(){ var w = window; w.m2 = function(){ return this.location.href }; return w.m2() });
T("this method identity", function(){ window.m = function(){ return this === PW ? "pw" : this === RW ? "rw" : "?" }; return window.m() });
T("this tagged", function(){ var w = window; w.tag = function(s){ return this === PW ? "pw" : this === RW ? "rw" : "?" }; return w.tag`x` });
T("this alias", function(){ var w = window; w.m3 = function(){ var self = this; return self.location.href }; return w.m3() });
T("this escape", function(){ var w = window; w.m5 = function(){ return (function(x){ return x.location.href })(this) }; return w.m5() });
T("this arrow", function(){ var w = window; w.m7 = function(){ return (() => this.location.href)() }; return w.m7() });
T("this param default", function(){ var w = window; w.m9 = function(a = this.location.href){ return a }; return w.m9() });
T("this param default arrow", function(){ var w = window; w.mA = function(g = () => this.location.href){ return g() }; return w.mA() });
T("this derived", function(){ var w = window; w.mB = function(){ return this.document.location.href }; return w.mB() });
T("this document listener", function(){ var d = document, got; d.dispatchReal(function(){ got = this.location.href + this.defaultView.location.href }); return got });
T("this getter", function(){ Object.defineProperty(RW, "gg", { get: function(){ return this.location.href }, configurable: true }); var w = window; return w.gg });
T("this object method", function(){ var o = { m() { return this.location ? this.location.href : "none" } }; return o.m() + o.m.call(window) });
T("this constructor", function(){ function K(){ this.v = 1; return this } return new K().v });
T("this fluent", function(){ function F(){ } F.prototype.a = function(){ return this }; var f = new F(); return f.a() === f });
T("this generator", function(){ var w = window; w.gen = function*(){ yield this.location.href }; return w.gen().next().value });
T("this async", function(){ var w = window, r; w.as = async function(){ r = this.location.href }; w.as(); return r });
T("this strict", function(){ "use strict"; var w = window; w.st = function(){ "use strict"; return this.location.href }; return w.st() });
T("this call apply", function(){ function g(){ return this.location.href } return g.call(window) + g.apply(document) });
T("this bind", function(){ function g(){ return this.location.href } return g.bind(window)() });
T("this with eval", function(){ var w = window; w.ev = function(){ return eval("this.location.href") }; return w.ev() });
T("this in class extends", function(){ var w = window; w.ce = function(){ class Q extends (this.location.href ? Object : Object) {} return "ok" }; return w.ce() });
T("this call receiver", function(){ var w = window; function g(){ return this.location.href } w.cr = function(){ return g.call(this) + g.apply(this, []) + g.bind(this)() }; return w.cr() });
T("self safe only", function(){ var w = window; w.sa = function(){ var self = this; return String(self.innerWidth) }; return w.sa() });
T("self closure escape", function(){ var w = window; w.sb = function(){ var self = this; return function(){ return self.location.href } }; return w.sb()() });
T("self returned", function(){ var w = window; w.sc = function(){ var self = this; return self }; return w.sc().location.href });
T("self passed", function(){ var w = window; function g(x){ return x.location.href } w.sd = function(){ var self = this; return g(self) }; return w.sd() });
T("self chain", function(){ var w = window; w.se = function(){ var self = this, that = self, other; other = that; return other.location.href }; return w.se() });
T("self derived", function(){ var w = window; w.sf = function(){ var self = this; var d = self.document; return d.location.href }; return w.sf() });
T("self mixed with global", function(){ var w = window; w.sg = function(){ var x = this || window; return x.location.href }; return w.sg() });
T("self in param", function(){ var w = window; w.sh = function(){ return (function(s){ return s.location.href })(this) }; return w.sh() });
T("self computed", function(){ var w = window; w.si = function(k){ var self = this; return self[k].href }; return w.si("location") });
T("self listener", function(){ var got; var w = window; w.addEventListener("x", function(){ var self = this; got = self.location.href }); w.dispatchReal(); return got });
T("this top parent", function(){ var w = window; w.tp = function(){ return String(this.top === PW) + String(this.parent === PW) + this.top.location.href }; return w.tp() });
T("this top on object", function(){ var o = { top: 5, parent: { location: { href: "p" } }, m() { return this.top + this.parent.location.href } }; return o.m() });
T("this location on object", function(){ var o = { location: { href: "own" }, m() { return this.location.href } }; return o.m() });
T("this eval", function(){ var w = window; w.te = function(){ return this.eval("1") }; return w.te() });
T("this location set", function(){ var w = window; w.ts = function(){ this.location = "/n"; return "ok" }; return w.ts() });
