import { probeTest } from "./harness.ts";

// CSS write-path x read-path matrix. Every probe returns what the page reads
// back; images are named `<run>-<probe>` so the origin log shows which writes
// actually reached the origin (rewritten correctly) and at which path.
const probes: Record<string, string> = {
	// ---- inline style, element CSSOM
	w_camel: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-w_camel.png)'; return [d.style.backgroundImage, d.getAttribute('style'), d.style.cssText];`,
	w_camel_rel: `const d=mk(); d.style.backgroundImage='url(img/'+R+'-w_camel_rel.png)'; return [d.style.backgroundImage];`,
	w_setprop_imp: `const d=mk(); d.style.setProperty('background-image','url(/img/'+R+'-w_setprop_imp.png)','important'); return [d.style.getPropertyPriority('background-image'), d.style.cssText, d.getAttribute('style')];`,
	w_setprop_imp_upper: `const d=mk(); d.style.setProperty('background-image','url(/img/'+R+'-w_setprop_imp_upper.png)','IMPORTANT'); return [d.style.getPropertyPriority('background-image'), d.style.cssText];`,
	w_setprop_null_prio: `const d=mk(); d.style.setProperty('color','red', null); d.style.setProperty('color','blue', undefined); return [d.style.cssText];`,
	w_setprop_num: `const d=mk(); d.style.setProperty('opacity', 0.5); d.style.setProperty('--n', 0); return [d.style.cssText];`,
	w_shorthand: `const d=mk(); d.style.background='url(/img/'+R+'-w_shorthand.png) no-repeat red'; return [d.style.background, d.style.backgroundImage, d.style.cssText];`,
	w_cssText: `const d=mk(); d.style.cssText='color:red; background-image:url(/img/'+R+'-w_cssText.png) !important'; return [d.style.cssText, d.getAttribute('style'), d.style.getPropertyPriority('background-image')];`,
	w_putforwards: `const d=mk(); d.style='color:red; background-image:url(/img/'+R+'-w_putforwards.png)'; return [d.style.cssText, d.getAttribute('style')];`,
	w_putforwards_svg: `const s=mksvg(); s.style='background-image:url(/img/'+R+'-w_putforwards_svg.png)'; return [s.style.cssText, s.getAttribute('style')];`,
	w_assign: `const d=mk(); Object.assign(d.style,{backgroundImage:'url(/img/'+R+'-w_assign.png)', color:'red'}); return [d.getAttribute('style')];`,
	w_custom: `const d=mk(); d.style.setProperty('--bg','url(/img/'+R+'-w_custom.png)'); d.style.backgroundImage='var(--bg)'; return [d.style.getPropertyValue('--bg'), d.style.cssText, d.getAttribute('style')];`,
	w_custom_rel: `const d=mk(); d.style.setProperty('--bg','url(img/'+R+'-w_custom_rel.png)'); d.style.backgroundImage='var(--bg)'; return [d.style.getPropertyValue('--bg')];`,
	w_removeProperty: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_rm.png)'; const r=d.style.removeProperty('background-image'); return [r, d.getAttribute('style'), d.style.length];`,
	w_cssFloat: `const d=mk(); d.style.cssFloat='left'; return [d.style.cssFloat, d.style.float, d.getAttribute('style')];`,
	w_float_attr: `const d=mk(); d.style.float='right'; return [d.style.cssFloat, d.getAttribute('style')];`,
	w_number: `const d=mk(); d.style.zIndex=5; d.style.opacity=null; d.style.lineHeight=2; return [d.style.cssText, d.getAttribute('style')];`,
	w_obj_tostring: `const d=mk(); d.style.width={toString(){return '3px'}}; return [d.style.width];`,
	w_typedom_val: `const d=mk(); d.style.width=CSS.px(7); return [d.style.width];`,
	w_empty_removes: `const d=mk(); d.style.color='red'; d.style.color=''; return [d.getAttribute('style'), d.hasAttribute('style')];`,
	w_webkit_lower: `const d=mk(); d.style.webkitMaskImage='url(/img/'+R+'-w_webkit_lower.png)'; return [d.style.webkitMaskImage];`,
	w_list_style: `const d=mk('ul'); d.innerHTML='<li>x</li>'; d.style.listStyleImage='url(/img/'+R+'-w_list_style.png)'; return [d.style.listStyleImage];`,
	w_border_image: `const d=mk(); d.style.borderStyle='solid'; d.style.borderWidth='2px'; d.style.borderImage='url(/img/'+R+'-w_border_image.png) 1 stretch'; return [d.style.borderImage, d.style.borderImageSource];`,
	w_multi_bg: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-w_multi_bg1.png), url("/img/'+R+'-w_multi_bg2.png")'; return [d.style.backgroundImage];`,
	// ---- attribute and markup
	w_attr: `const d=mk(); d.setAttribute('style','background-image:url(/img/'+R+'-w_attr.png)'); return [d.getAttribute('style'), d.style.backgroundImage, d.style.cssText];`,
	w_attr_then_prop: `const d=mk(); d.setAttribute('style','background-image:url(/img/'+R+'-x_atp.png); color:red'); d.style.color='blue'; return [d.getAttribute('style'), d.style.backgroundImage];`,
	w_attrnode: `const d=mk(); const a=document.createAttribute('style'); a.value='background-image:url(/img/'+R+'-w_attrnode.png)'; d.setAttributeNode(a); return [d.getAttribute('style'), a.value, d.style.backgroundImage];`,
	w_attrvalue: `const d=mk(); d.setAttribute('style','color:red'); d.attributes.style.value='background-image:url(/img/'+R+'-w_attrvalue.png)'; return [d.getAttribute('style'), d.style.backgroundImage];`,
	w_innerhtml: `const h=mk(); h.innerHTML='<div style="width:4px;height:4px;background-image:url(/img/'+R+'-w_innerhtml.png)"></div>'; const d=h.firstChild; return [d.getAttribute('style'), d.style.backgroundImage, h.innerHTML];`,
	w_outerhtml_after_prop: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_oh.png)'; return [d.outerHTML];`,
	w_clone_after_prop: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_cl.png)'; const c=d.cloneNode(); return [c.getAttribute('style'), c.style.backgroundImage];`,
	// ---- typed OM
	w_typed_str: `const d=mk(); d.attributeStyleMap.set('background-image','url(/img/'+R+'-w_typed_str.png)'); return [d.style.backgroundImage, d.getAttribute('style')];`,
	w_typed_parse: `const d=mk(); d.attributeStyleMap.set('background-image', CSSStyleValue.parse('background-image','url(/img/'+R+'-w_typed_parse.png)')); return [d.style.backgroundImage];`,
	w_typed_unparsed: `const d=mk(); d.attributeStyleMap.set('--bg', new CSSUnparsedValue(['url(/img/'+R+'-w_typed_unparsed.png)'])); d.style.backgroundImage='var(--bg)'; return [d.style.getPropertyValue('--bg')];`,
	w_typed_append: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-w_typed_append1.png)'; d.attributeStyleMap.append('background-image','url(/img/'+R+'-w_typed_append2.png)'); return [d.style.backgroundImage];`,
	w_typed_num: `const d=mk(); d.attributeStyleMap.set('opacity', 0.5); d.attributeStyleMap.set('width', CSS.px(4)); return [d.style.cssText, d.getAttribute('style')];`,
	w_typed_get_roundtrip: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-w_typed_get_roundtrip.png)'; const v=d.attributeStyleMap.get('background-image'); const d2=mk(); d2.attributeStyleMap.set('background-image', v); return [d2.style.backgroundImage];`,
	w_typed_other_el: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_toe.png)'; const d2=mk(); d2.attributeStyleMap.set('background-image', d.attributeStyleMap.get('background-image')); return [d2.getAttribute('style')];`,
	// ---- svg / mathml
	w_svg_prop: `const s=mksvg(); s.style.backgroundImage='url(/img/'+R+'-w_svg_prop.png)'; return [s.style.backgroundImage, s.getAttribute('style')];`,
	w_svg_attr: `const s=mksvg(); s.setAttribute('style','background-image:url(/img/'+R+'-w_svg_attr.png)'); return [s.style.backgroundImage, s.getAttribute('style')];`,
	w_svg_nonurl: `const s=mksvg(); s.style.fill='red'; s.style.strokeWidth='2'; return [s.style.fill, s.getAttribute('style')];`,
	w_mathml: `const m=document.createElementNS('http://www.w3.org/1998/Math/MathML','math'); m.style.display='block'; m.style.width='4px'; m.style.height='4px'; document.body.appendChild(m); m.style.backgroundImage='url(/img/'+R+'-w_mathml.png)'; return [m.style.backgroundImage, m.getAttribute('style')];`,
	// ---- sheets and rules
	w_insertRule: `const sh=inl(); sh.insertRule('.c_w_insertRule{background-image:url(img/'+R+'-w_insertRule.png)}'); mk().className='c_w_insertRule'; return [sh.cssRules[0].cssText, sh.cssRules[0].style.backgroundImage];`,
	w_insertRule_ext: `const sh=ext(); sh.insertRule('.c_w_insertRule_ext{background-image:url(img/'+R+'-w_insertRule_ext.png)}'); mk().className='c_w_insertRule_ext'; return [sh.cssRules[0].cssText];`,
	w_rulestyle_ext: `const sh=ext(); const r=[...sh.cssRules].find(r=>r.selectorText==='.e1'); r.style.backgroundImage='url(img/'+R+'-w_rulestyle_ext.png)'; mk().className='e1'; return [r.style.backgroundImage, r.cssText];`,
	w_rulestyle_ext_setprop: `const sh=ext(); const r=[...sh.cssRules].find(r=>r.selectorText==='.e2'); r.style.setProperty('background-image','url(img/'+R+'-w_rulestyle_ext_setprop.png)'); mk().className='e2'; return [r.style.backgroundImage];`,
	w_rulestyle_ext_cssText: `const sh=ext(); const r=[...sh.cssRules].find(r=>r.selectorText==='.e3'); r.style.cssText='background-image:url(img/'+R+'-w_rulestyle_ext_cssText.png)'; mk().className='e3'; return [r.style.backgroundImage];`,
	w_rulestyle_ext_read: `const sh=ext(); const r=[...sh.cssRules].find(r=>r.selectorText==='.e4'); return [r.style.backgroundImage, r.style.getPropertyValue('background-image'), r.cssText];`,
	w_rulestyle_inl: `const sh=inl(); sh.insertRule('.c_w_rulestyle_inl{}'); sh.cssRules[0].style.backgroundImage='url(img/'+R+'-w_rulestyle_inl.png)'; mk().className='c_w_rulestyle_inl'; return [sh.cssRules[0].style.backgroundImage, sh.cssRules[0].cssText];`,
	w_rule_selectorText: `const sh=inl(); sh.insertRule('.zz{color:red}'); sh.cssRules[0].selectorText='.c_w_rule_selectorText'; return [sh.cssRules[0].selectorText];`,
	w_rule_cssText_set: `const sh=inl(); sh.insertRule('.zz2{color:red}'); try{ sh.cssRules[0].cssText='.q{color:blue}'; }catch(e){ return 'THROW '+e.name } return [sh.cssRules[0].cssText];`,
	w_addRule: `const sh=inl(); const n=sh.addRule('.c_w_addRule','background-image:url(img/'+R+'-w_addRule.png)'); mk().className='c_w_addRule'; return [n, sh.cssRules[sh.cssRules.length-1].cssText];`,
	w_addRule_noargs: `const sh=inl(); const n=sh.addRule(); return [n, sh.cssRules[sh.cssRules.length-1].cssText];`,
	w_deleteRule: `const sh=inl(); sh.insertRule('.dd{color:red}'); sh.deleteRule(0); return [sh.cssRules.length];`,
	w_replaceSync_doc: `const sh=new CSSStyleSheet(); sh.replaceSync('.c_w_replaceSync_doc{background-image:url(img/'+R+'-w_replaceSync_doc.png)}'); document.adoptedStyleSheets=[...document.adoptedStyleSheets, sh]; mk().className='c_w_replaceSync_doc'; return [sh.cssRules[0].cssText];`,
	w_replace_async: `const sh=new CSSStyleSheet(); const p=sh.replace('.c_w_replace_async{background-image:url(img/'+R+'-w_replace_async.png)}'); const r=await p; document.adoptedStyleSheets=[...document.adoptedStyleSheets, sh]; mk().className='c_w_replace_async'; return [r===sh, sh.cssRules[0].cssText];`,
	w_replace_reject: `const sh=document.getElementById('st1').sheet; try { await sh.replace('.a{}'); return 'resolved'; } catch(e){ return 'REJ '+e.name; }`,
	w_replace_shadow: `const h=mk(); const sr=h.attachShadow({mode:'open'}); sr.innerHTML='<div class=c style="width:4px;height:4px"></div>'; const sh=new CSSStyleSheet(); sh.replaceSync('.c{background-image:url(img/'+R+'-w_replace_shadow.png)}'); sr.adoptedStyleSheets=[sh]; return [sh.cssRules[0].cssText, sr.adoptedStyleSheets.length];`,
	w_constructed_baseURL: `const sh=new CSSStyleSheet({baseURL: location.origin + '/css/'}); sh.replaceSync('.c_w_constructed_baseURL{background-image:url(img/'+R+'-w_constructed_baseURL.png)}'); document.adoptedStyleSheets=[...document.adoptedStyleSheets, sh]; mk().className='c_w_constructed_baseURL'; return [sh.cssRules[0].cssText];`,
	w_constructed_media: `const sh=new CSSStyleSheet({media:'print'}); sh.replaceSync('.x{color:red}'); return [sh.media.mediaText, sh.cssRules.length];`,
	w_constructed_insert_rel: `const sh=new CSSStyleSheet(); sh.insertRule('.c_w_constructed_insert_rel{background-image:url(img/'+R+'-w_constructed_insert_rel.png)}'); document.adoptedStyleSheets=[...document.adoptedStyleSheets, sh]; mk().className='c_w_constructed_insert_rel'; return [sh.cssRules[0].cssText];`,
	w_import_insertRule: `const s=document.createElement('style'); document.head.appendChild(s); s.sheet.insertRule('@import url(/css/'+R+'-imp.css);'); await new Promise(r=>setTimeout(r,300)); return [s.sheet.cssRules[0].cssText, !!s.sheet.cssRules[0].styleSheet && s.sheet.cssRules[0].styleSheet.cssRules.length];`,
	w_fontface_rule: `const s=document.createElement('style'); s.textContent='@font-face{font-family:FF_'+R+'; src:url(/img/'+R+'-w_fontface_rule.woff2)}'; document.head.appendChild(s); try{ await document.fonts.load('10px FF_'+R); }catch(e){} return [s.sheet.cssRules[0].cssText, s.sheet.cssRules[0].style.getPropertyValue('src')];`,
	w_fontface_js: `const f=new FontFace('FJ_'+R, 'url(/img/'+R+'-w_fontface_js.woff2)'); try{ await f.load(); }catch(e){} return [f.family, f.status];`,
	w_fontface_rule_setprop: `const s=document.createElement('style'); s.textContent='@font-face{font-family:FS_'+R+'; src:url(/nothing.woff2)}'; document.head.appendChild(s); s.sheet.cssRules[0].style.setProperty('src','url(/img/'+R+'-w_fontface_rule_setprop.woff2)'); try{ await document.fonts.load('10px FS_'+R); }catch(e){} return [s.sheet.cssRules[0].cssText];`,
	w_registerProperty: `try { CSS.registerProperty({name:'--rp'+R, syntax:'<url>', inherits:false, initialValue:'url(/img/'+R+'-w_registerProperty.png)'}); } catch(e){ return 'THROW '+e.name+' '+e.message; } const d=mk(); d.style.backgroundImage='var(--rp'+R+')'; return [getComputedStyle(d).getPropertyValue('--rp'+R).includes('/~/sj/')];`,
	w_property_rule: `const s=document.createElement('style'); s.textContent='@property --pr'+R+'{syntax:"<url>"; inherits:false; initial-value:url(/img/'+R+'-w_property_rule.png)} .c_w_property_rule{background-image:var(--pr'+R+')}'; document.head.appendChild(s); mk().className='c_w_property_rule'; return [s.sheet.cssRules.length];`,
	w_animate: `const d=mk(); const a=d.animate([{backgroundImage:'url(/img/'+R+'-w_animate1.png)'},{backgroundImage:'url(/img/'+R+'-w_animate2.png)'}],{duration:100000, fill:'forwards'}); return [a.effect.getKeyframes()[0].backgroundImage];`,
	w_layer_media: `const s=document.createElement('style'); s.textContent='@layer a{ @media all { .c_w_layer_media{background-image:url(img/'+R+'-w_layer_media.png)} } }'; document.head.appendChild(s); mk().className='c_w_layer_media'; return [s.textContent];`,
	w_container: `const s=document.createElement('style'); s.textContent='@container (min-width:0px){ .c_w_container{background-image:url(img/'+R+'-w_container.png)} }'; document.head.appendChild(s); const h=mk(); h.style.containerType='inline-size'; h.style.width='10px'; const d=document.createElement('div'); d.className='c_w_container'; d.style.cssText='width:4px;height:4px'; h.appendChild(d); return [s.sheet.cssRules[0].cssText];`,
	// ---- <style> text
	w_style_text: `const s=document.createElement('style'); s.textContent='.c_w_style_text{background-image:url(img/'+R+'-w_style_text.png)}'; document.head.appendChild(s); mk().className='c_w_style_text'; return [s.textContent, s.innerHTML, s.sheet.cssRules[0].cssText];`,
	w_style_append: `const s=document.createElement('style'); document.head.appendChild(s); s.appendChild(document.createTextNode('.c_w_style_append1{background-image:url(img/'+R+'-w_style_append1.png)}')); s.appendChild(document.createTextNode('.c_w_style_append2{background-image:url(img/'+R+'-w_style_append2.png)}')); mk().className='c_w_style_append1'; mk().className='c_w_style_append2'; return [s.childNodes.length, s.childNodes[0].data, s.childNodes[1].data, s.childNodes[0].length, s.sheet.cssRules.length];`,
	w_style_data: `const s=document.createElement('style'); s.appendChild(document.createTextNode('')); document.head.appendChild(s); s.firstChild.data += '.c_w_style_data{background-image:url(img/'+R+'-w_style_data.png)}'; mk().className='c_w_style_data'; return [s.firstChild.data, s.sheet.cssRules.length];`,
	w_style_remove_first: `const s=document.createElement('style'); document.head.appendChild(s); const a=document.createTextNode('.c_w_style_remove_first_a{color:red}'); const b=document.createTextNode('.c_w_style_remove_first{background-image:url(img/'+R+'-w_style_remove_first.png)}'); s.append(a,b); s.removeChild(a); mk().className='c_w_style_remove_first'; return [s.textContent, s.sheet.cssRules.length, s.sheet.cssRules[0] && s.sheet.cssRules[0].selectorText];`,
	w_style_innerHTML: `const s=document.createElement('style'); s.innerHTML='.c_w_style_innerHTML{background-image:url(img/'+R+'-w_style_innerHTML.png)}'; document.head.appendChild(s); mk().className='c_w_style_innerHTML'; return [s.innerHTML];`,
	w_style_svg: `const s=mksvg(); const st=document.createElementNS('http://www.w3.org/2000/svg','style'); st.textContent='.c_w_style_svg{background-image:url(img/'+R+'-w_style_svg.png)}'; s.appendChild(st); mk().className='c_w_style_svg'; return [st.textContent, st.sheet && st.sheet.cssRules.length];`,
	w_style_cssom_then_text: `const s=document.createElement('style'); s.appendChild(document.createTextNode('')); document.head.appendChild(s); s.sheet.insertRule('.c_w_style_cssom_then_text{color:red}'); s.setAttribute('data-x','1'); return [s.sheet.cssRules.length];`,
	w_style_move: `const s=document.createElement('style'); s.appendChild(document.createTextNode('')); document.head.appendChild(s); s.sheet.insertRule('.moved{color:red}'); document.body.appendChild(s); document.head.appendChild(s); return [s.sheet.cssRules.length];`,
	w_link: `const l=document.createElement('link'); l.rel='stylesheet'; l.href='css/'+R+'-lnk.css'; document.head.appendChild(l); await new Promise(r=>{l.onload=r; l.onerror=r; setTimeout(r,1500)}); mk().className='lnk'; return [l.href, l.getAttribute('href'), l.sheet && l.sheet.cssRules.length];`,
	w_link_change: `const l=document.createElement('link'); l.rel='stylesheet'; l.href='/css/'+R+'-lnkA.css'; document.head.appendChild(l); await new Promise(r=>{l.onload=r; l.onerror=r; setTimeout(r,1500)}); l.href='/css/'+R+'-lnkB.css'; await new Promise(r=>{l.onload=r; l.onerror=r; setTimeout(r,1500)}); return [l.href];`,
	// ---- non-URL values the url regex might mangle
	v_content_url: `const d=mk(); d.style.content='"see url(x.png) here"'; return [d.style.content, d.getAttribute('style')];`,
	v_content_cssText: `const d=mk(); d.style.cssText='content:"url(y)"'; return [d.style.content];`,
	v_comment: `const d=mk(); d.setAttribute('style','color:red /* url(c.png) */'); return [d.getAttribute('style'), d.style.color];`,
	v_data_svg: `const d=mk(); const v='url("data:image/svg+xml;utf8,<svg xmlns=\\'http://www.w3.org/2000/svg\\' width=\\'1\\' height=\\'1\\'><rect width=\\'1\\' height=\\'1\\' fill=\\'%23f00\\'/></svg>")'; d.style.backgroundImage=v; return [d.style.backgroundImage===v, d.style.backgroundImage];`,
	v_data_parens_escaped: `const d=mk(); d.style.backgroundImage='url(data:image/svg+xml;utf8,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22%3E%3Crect style=%22fill:rgb\\\\(1,2,3\\\\)%22/%3E%3C/svg%3E)'; return [d.style.backgroundImage];`,
	v_escaped_quote: `const d=mk(); d.style.backgroundImage='url("/img/'+R+'-v_esc\\\\"q.png")'; return [d.style.backgroundImage];`,
	v_upper_URL: `const d=mk(); d.style.backgroundImage='URL(/img/'+R+'-v_upper_URL.png)'; return [d.style.backgroundImage];`,
	v_dollar: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-v_dollar$&x.png)'; return [d.style.backgroundImage];`,
	v_substr: `const d=mk(); d.style.backgroundImage='url(u)'; return [d.style.backgroundImage];`,
	v_blob: `const b=new Blob([PNGBYTES],{type:'image/png'}); const u=URL.createObjectURL(b); const d=mk(); d.style.backgroundImage='url('+u+')'; await new Promise(r=>setTimeout(r,200)); return [d.style.backgroundImage==='url("'+u+'")', d.style.backgroundImage.slice(0,40)];`,
	v_blob_svg: `const b=new Blob([PNGBYTES],{type:'image/png'}); const u=URL.createObjectURL(b); const s=mksvg(); s.style.backgroundImage='url('+u+')'; return [s.style.backgroundImage==='url("'+u+'")'];`,
	v_blob_rule: `const b=new Blob([PNGBYTES],{type:'image/png'}); const u=URL.createObjectURL(b); const sh=inl(); sh.insertRule('.bb{}'); sh.cssRules[0].style.backgroundImage='url('+u+')'; return [sh.cssRules[0].style.backgroundImage==='url("'+u+'")'];`,
	v_data_rule: `const sh=inl(); sh.insertRule('.dr{}'); sh.cssRules[0].style.backgroundImage='url(data:image/png;base64,iVBORw0KGgo=)'; return [sh.cssRules[0].style.backgroundImage];`,
	v_about: `const d=mk(); d.style.backgroundImage='url(about:blank)'; return [d.style.backgroundImage];`,
	v_frag_html: `const d=mk(); d.style.filter='url(#f)'; return [d.style.filter];`,
	v_empty_url: `const d=mk(); d.style.backgroundImage='url()'; d.style.cursor='url("") , auto'; return [d.style.cssText];`,
	v_image_set: `const d=mk(); d.style.backgroundImage='image-set(url(/img/'+R+'-v_image_set.png) 1x)'; return [d.style.backgroundImage];`,
	v_src_font_rule: `const s=document.createElement('style'); s.textContent='@font-face{font-family:Y; src:local(Arial), url(/f.woff2) format("woff2")}'; document.head.appendChild(s); return [s.sheet.cssRules[0].cssText, s.textContent];`,
	// ---- reads
	r_length_item: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_li.png)'; d.style.color='red'; return [d.style.length, d.style.item(0), d.style[0], d.style[1]];`,
	r_forin: `const d=mk(); d.style.color='red'; let n=0, hasColor=false; for (const k in d.style){ n++; if(k==='color') hasColor=true; } return [n>100, hasColor, Object.keys(d.style).length>0];`,
	r_getpv_computed: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_gc.png)'; const cs=getComputedStyle(d); return [cs.getPropertyValue('background-image').includes('/~/sj/'), cs.backgroundImage.includes('/~/sj/')];`,
	r_style_identity: `const d=mk(); const s=d.style; return [s===d.style, s.setProperty===d.style.setProperty, s.setProperty===CSSStyleDeclaration.prototype.setProperty, s instanceof CSSStyleDeclaration, s.constructor===Object.getPrototypeOf(s).constructor, Object.prototype.toString.call(s)];`,
	r_svg_identity: `const s=mksvg(); return [s.style===s.style, s.style.getPropertyValue===CSSStyleDeclaration.prototype.getPropertyValue];`,
	r_rule_identity: `const sh=inl(); sh.insertRule('.ri{color:red}'); const r=sh.cssRules[0]; return [r.style===r.style, r.style.parentRule===r];`,
	r_desc: `const d=mk(); d.style.color='red'; const desc=Object.getOwnPropertyDescriptor(d.style,'color'); return desc ? [desc.value, desc.writable, desc.enumerable, desc.configurable] : 'none';`,
	r_mo_old: `const d=mk(); d.setAttribute('style','background-image:url(/img/'+R+'-x_mo1.png)'); const recs=[]; const mo=new MutationObserver(r=>recs.push(...r)); mo.observe(d,{attributes:true, attributeOldValue:true}); d.setAttribute('style','color:red'); d.style.color='blue'; await new Promise(r=>setTimeout(r,20)); mo.disconnect(); return recs.map(r=>[r.attributeName, r.oldValue]);`,
	r_mo_filter: `const d=mk(); const recs=[]; const mo=new MutationObserver(r=>recs.push(...r)); mo.observe(d,{attributeFilter:['style']}); d.style.color='blue'; d.style.setProperty('width','3px'); await new Promise(r=>setTimeout(r,20)); mo.disconnect(); return recs.map(r=>r.attributeName);`,
	r_roundtrip_cssText: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_rt.png)'; const t=d.style.cssText; const d2=mk(); d2.style.cssText=t; return [d2.style.cssText===t, t];`,
	r_roundtrip_attr: `const d=mk(); d.style.backgroundImage='url(/img/'+R+'-x_rta.png)'; const d2=mk(); d2.setAttribute('style', d.getAttribute('style')); return [d2.style.backgroundImage===d.style.backgroundImage];`,
	// ---- other contexts
	c_blank_iframe: `const f=document.createElement('iframe'); document.body.appendChild(f); const b=f.contentDocument.body; b.innerHTML='<div style="width:4px;height:4px"></div>'; const d=b.firstChild; d.style.backgroundImage='url(/img/'+R+'-c_blank_iframe.png)'; await new Promise(r=>setTimeout(r,300)); return [d.style.backgroundImage];`,
	c_blank_iframe_rel: `const f=document.createElement('iframe'); document.body.appendChild(f); const b=f.contentDocument.body; b.innerHTML='<div style="width:4px;height:4px"></div>'; const d=b.firstChild; d.style.backgroundImage='url(img/'+R+'-c_blank_iframe_rel.png)'; await new Promise(r=>setTimeout(r,300)); return [d.style.backgroundImage];`,
	c_srcdoc: `const f=document.createElement('iframe'); f.srcdoc='<div id=q style="width:4px;height:4px"></div><script>document.getElementById("q").style.backgroundImage="url(img/'+R+'-c_srcdoc.png)"; document.getElementById("q").style.setProperty("border-image-source","url(/img/'+R+'-c_srcdoc2.png)");<\\/script>'; document.body.appendChild(f); await new Promise(r=>f.onload=r); await new Promise(r=>setTimeout(r,300)); return [f.contentDocument.getElementById('q').style.backgroundImage];`,
	c_subframe: `const f=document.createElement('iframe'); f.src='/sub.html?r='+R; document.body.appendChild(f); await new Promise(r=>f.onload=r); await new Promise(r=>setTimeout(r,500)); return [f.contentWindow.__res];`,
	c_parent_writes_child_el: `const f=document.createElement('iframe'); f.src='/sub.html?r=none'; document.body.appendChild(f); await new Promise(r=>f.onload=r); const d=f.contentDocument.createElement('div'); d.style.cssText='width:4px;height:4px'; f.contentDocument.body.appendChild(d); d.style.backgroundImage='url(img/'+R+'-c_parent_writes_child_el.png)'; await new Promise(r=>setTimeout(r,300)); return [d.style.backgroundImage];`,
};

export default [probeTest("rv18-cssmatrix", probes)];
