import { basicTest } from "../../../testcommon.ts";

// Edge-case argument conversions on intercepted members, compared against
// bare Chrome with assertConsistent (run WITHOUT RUNWAY_FAST).
const battery = String.raw`
const R = (fn) => { try { const v = fn(); if (v && typeof v.then === "function") return "promise"; return typeof v === "object" && v !== null ? (v.nodeName || Object.prototype.toString.call(v)) : String(v); } catch (e) { return "THROW " + e.name + ": " + e.message; } };
const el = () => { const d = document.createElement("div"); document.body.appendChild(d); return d; };
const cases = {
	setAttrNull: () => { const d = el(); d.setAttribute("title", null); return d.getAttribute("title"); },
	setAttrUndef: () => { const d = el(); d.setAttribute("title", undefined); return d.getAttribute("title"); },
	setAttrObj: () => { const d = el(); d.setAttribute("title", { toString() { return "T"; } }); return d.getAttribute("title"); },
	setAttrNameNull: () => { const d = el(); d.setAttribute(null, "x"); return d.getAttribute("null"); },
	setAttrOneArg: () => { const d = el(); d.setAttribute("title"); },
	getAttrUndef: () => { const d = el(); return d.getAttribute(undefined); },
	getAttrNone: () => { const d = el(); return d.getAttribute(); },
	hasAttrNull: () => el().hasAttribute(null),
	toggleAttrUndef: () => { const d = el(); return d.toggleAttribute("x", undefined) + "," + d.hasAttribute("x"); },
	setAttrNSUndef: () => { const d = el(); d.setAttributeNS(undefined, "a", "b"); return d.getAttributeNS(null, "a"); },
	removeAttrUndef: () => { const d = el(); d.setAttribute("undefined", "1"); d.removeAttribute(undefined); return d.hasAttribute("undefined"); },
	appendMixed: () => { const d = el(); d.append(null, undefined, 1, {}, "s"); return d.textContent; },
	appendNone: () => { const d = el(); d.append(); return d.childNodes.length; },
	prependSym: () => { const d = el(); d.prepend(Symbol("x")); },
	insertBeforeUndef: () => { const d = el(); const s = document.createElement("span"); d.insertBefore(s, undefined); return d.firstChild === s; },
	insertBeforeNull: () => { const d = el(); d.appendChild(document.createElement("i")); const s = document.createElement("span"); d.insertBefore(s, null); return d.lastChild === s; },
	insertBeforeOneArg: () => { const d = el(); d.insertBefore(document.createElement("span")); },
	appendChildText: () => el().appendChild("text"),
	appendChildNull: () => el().appendChild(null),
	replaceChildMissing: () => { const d = el(); d.replaceChild(document.createElement("a")); },
	removeChildNonChild: () => el().removeChild(document.createElement("a")),
	innerHTMLNull: () => { const d = el(); d.innerHTML = "<b>x</b>"; d.innerHTML = null; return d.innerHTML + "|" + d.childNodes.length; },
	innerHTMLUndef: () => { const d = el(); d.innerHTML = undefined; return d.innerHTML; },
	innerHTMLObj: () => { const d = el(); d.innerHTML = { toString() { return "<i>o</i>"; } }; return d.innerHTML; },
	outerHTMLDetached: () => { const d = document.createElement("div"); d.outerHTML = "<p></p>"; return d.outerHTML; },
	textContentNull: () => { const d = el(); d.textContent = "x"; d.textContent = null; return d.textContent + "|" + d.childNodes.length; },
	textContentUndef: () => { const d = el(); d.textContent = undefined; return d.textContent; },
	textContentNum: () => { const d = el(); d.textContent = 5; return d.textContent; },
	innerTextNull: () => { const d = el(); d.innerText = null; return d.innerText + "|" + d.childNodes.length; },
	nodeValueNull: () => { const t = document.createTextNode("a"); t.nodeValue = null; return JSON.stringify(t.nodeValue); },
	dataNull: () => { const t = document.createTextNode("a"); t.data = null; return JSON.stringify(t.data); },
	scriptTextNull: () => { const s = document.createElement("script"); s.text = null; return JSON.stringify(s.text); },
	scriptTextContentNull: () => { const s = document.createElement("script"); s.textContent = null; return JSON.stringify(s.textContent); },
	insertAdjNull: () => { const d = el(); d.insertAdjacentHTML("beforeend", null); return d.innerHTML; },
	insertAdjBadPos: () => { const d = el(); d.insertAdjacentHTML("nope", "x"); },
	insertAdjTextUndef: () => { const d = el(); d.insertAdjacentText("beforeend", undefined); return d.textContent; },
	insertAdjElNull: () => el().insertAdjacentElement("beforeend", null),
	aHrefNull: () => { const a = document.createElement("a"); a.href = null; return a.getAttribute("href"); },
	aHrefUndef: () => { const a = document.createElement("a"); a.href = undefined; return a.getAttribute("href"); },
	aHrefEmpty: () => { const a = document.createElement("a"); a.href = ""; return a.getAttribute("href") + "|" + (a.href === location.href); },
	imgSrcNull: () => { const i = document.createElement("img"); i.src = null; return i.getAttribute("src"); },
	iframeSrcdocNull: () => { const f = document.createElement("iframe"); f.srcdoc = null; return JSON.stringify(f.getAttribute("srcdoc")); },
	linkHrefObj: () => { const l = document.createElement("link"); l.href = { toString() { return "/x.css"; } }; return l.getAttribute("href"); },
	formActionNull: () => { const f = document.createElement("form"); f.action = null; return f.getAttribute("action"); },
	classListAddUndef: () => { const d = el(); d.classList.add(undefined); return d.className; },
	classListToggleUndef: () => { const d = el(); return d.classList.toggle("a", undefined) + "|" + d.className; },
	classListAddEmpty: () => el().classList.add(""),
	classListAddSpace: () => el().classList.add("a b"),
	classListValueNull: () => { const d = el(); d.classList.value = null; return d.className; },
	styleSetPropNull: () => { const d = el(); d.style.setProperty("color", "red"); d.style.setProperty("color", null); return d.style.color; },
	styleCssTextNull: () => { const d = el(); d.style.cssText = "color:red"; d.style.cssText = null; return d.style.cssText; },
	stylePutForwards: () => { const d = el(); d.style = "color: blue"; return d.style.color; },
	styleBgUrl: () => { const d = el(); d.style.backgroundImage = "url(/a.png)"; return d.style.backgroundImage; },
	styleBgUrlCamelObj: () => { const d = el(); d.style.setProperty("background-image", { toString() { return "url(b.png)"; } }); return d.style.getPropertyValue("background-image"); },
	getCSUndef: () => typeof getComputedStyle(el(), undefined).color,
	getCSNull: () => typeof getComputedStyle(el(), null).color,
	getCSText: () => getComputedStyle("x"),
	getCSNone: () => getComputedStyle(),
	createElUndef: () => document.createElement(undefined).localName,
	createElNull: () => document.createElement(null).localName,
	createElBad: () => document.createElement("a b"),
	createElOpts: () => document.createElement("div", "x").localName,
	createElNSNull: () => document.createElementNS(null, "x").namespaceURI,
	setTimeoutStrDelay: () => { const id = setTimeout(() => {}, "abc"); clearTimeout(id); return typeof id; },
	setTimeoutNullFn: () => { const id = setTimeout(null, 0); clearTimeout(id); return typeof id; },
	setTimeoutNoArgs: () => setTimeout(),
	setTimeoutObjDelay: () => { let n = 0; const id = setTimeout(() => {}, { valueOf() { n++; return 5; } }); clearTimeout(id); return n; },
	setIntervalNeg: () => { const id = setInterval(() => {}, -5); clearInterval(id); return typeof id; },
	clearTimeoutStr: () => clearTimeout("abc"),
	pushStateOne: () => history.pushState({}),
	pushStateNullUrl: () => { history.pushState(null, "", null); return location.pathname; },
	pushStateUndefUrl: () => { history.pushState(null, "", undefined); return location.pathname; },
	pushStateSym: () => history.pushState(null, Symbol("x")),
	replaceStateObjUrl: () => { history.replaceState(null, "", { toString() { return "?q=1"; } }); return location.search; },
	replaceStateEmpty: () => { history.replaceState(null, "", ""); return location.search; },
	lsSetUndef: () => { localStorage.setItem(undefined, null); const v = localStorage.getItem("undefined"); localStorage.removeItem("undefined"); return v; },
	lsGetMissing: () => localStorage.getItem("nope-" + 1),
	lsSetOne: () => localStorage.setItem("a"),
	lsKeyStr: () => localStorage.key("abc"),
	lsLength: () => typeof localStorage.length,
	lsPropSet: () => { localStorage.foo = 1; const v = localStorage.getItem("foo"); delete localStorage.foo; return v + "|" + localStorage.getItem("foo"); },
	cookieNull: () => { document.cookie = null; return typeof document.cookie; },
	cookieObj: () => { document.cookie = { toString() { return "zz=1; path=/"; } }; const has = document.cookie.includes("zz=1"); document.cookie = "zz=; max-age=0; path=/"; return has; },
	xhrOpenUndefUrl: () => { const x = new XMLHttpRequest(); x.open("GET", undefined); return x.readyState; },
	xhrOpenBadMethod: () => { const x = new XMLHttpRequest(); x.open("GE T", "/"); },
	xhrOpenOne: () => { const x = new XMLHttpRequest(); x.open("GET"); },
	xhrSetHeaderNull: () => { const x = new XMLHttpRequest(); x.open("GET", "/"); x.setRequestHeader("x-a", null); return "ok"; },
	xhrSetHeaderBeforeOpen: () => new XMLHttpRequest().setRequestHeader("a", "b"),
	xhrGetRespHeaderUndef: () => new XMLHttpRequest().getResponseHeader(undefined),
	headersUndef: () => [...new Headers(undefined)].length,
	headersNull: () => new Headers(null),
	headersStr: () => new Headers("a"),
	headersAppendNull: () => { const h = new Headers(); h.append("a", null); return h.get("a"); },
	headersGetUndef: () => new Headers({ undefined: "1" }).get(undefined),
	headersBadName: () => new Headers().append("a b", "c"),
	headersIterPairs: () => JSON.stringify([...new Headers([["b", "2"], ["a", "1"]])]),
	headersObjWithSymbol: () => { const o = { a: "1" }; o[Symbol("s")] = "x"; return new Headers(o).get("a"); },
	respNull: () => typeof new Response(null).status,
	respUndefUndef: () => new Response(undefined, undefined).status,
	respBadStatus: () => new Response("", { status: 99 }),
	respRedirect: () => Response.redirect("/x", 302).headers.get("location"),
	respRedirectBad: () => Response.redirect("/x", 200),
	respJson: () => Response.json({ a: 1 }).headers.get("content-type"),
	reqUndef: () => new Request(undefined).url,
	reqObj: () => new Request({ toString() { return "/o"; } }).url,
	reqNone: () => new Request(),
	reqBadMethod: () => new Request("/", { method: "CONNECT" }),
	reqMode: () => new Request("/", { mode: "bogus" }),
	reqClone: () => new Request(new Request("/c", { method: "POST", body: "x" })).method,
	fetchNone: () => fetch(),
	fetchBadScheme: () => fetch("foo://bar"),
	fetchSymbol: () => fetch(Symbol("x")),
	urlCreateBad: () => URL.createObjectURL("x"),
	urlCreateNone: () => URL.createObjectURL(),
	sendBeaconNone: () => navigator.sendBeacon(),
	sendBeaconUrl: () => navigator.sendBeacon("/beacon-test", null),
	postMessageOne: () => { window.postMessage("x"); return "ok"; },
	postMessageBadOrigin: () => window.postMessage("x", "not a url"),
	postMessageNone: () => window.postMessage(),
	postMessageOpts: () => { window.postMessage("x", { targetOrigin: "*" }); return "ok"; },
	postMessageTransferBad: () => window.postMessage("x", "*", [1]),
	openNone: () => typeof window.open,
	dispatchNonEvent: () => el().dispatchEvent({}),
	dispatchNone: () => el().dispatchEvent(),
	aelNullCb: () => { el().addEventListener("x", null); return "ok"; },
	aelStrCb: () => el().addEventListener("x", "notfn"),
	aelObjCb: () => { const d = el(); let n = 0; d.addEventListener("x", { handleEvent() { n++; } }); d.dispatchEvent(new Event("x")); return n; },
	aelOptsStr: () => { const d = el(); let n = 0; d.addEventListener("x", () => n++, "true"); d.dispatchEvent(new Event("x")); return n; },
	aelOnce: () => { const d = el(); let n = 0; d.addEventListener("x", () => n++, { once: 1 }); d.dispatchEvent(new Event("x")); d.dispatchEvent(new Event("x")); return n; },
	aelNoArgs: () => el().addEventListener("x"),
	relNone: () => el().removeEventListener("x"),
	onclickStr: () => { const d = el(); d.onclick = "notfn"; return String(d.onclick); },
	onclickObj: () => { const d = el(); d.onclick = {}; return String(d.onclick); },
	onclickNum: () => { const d = el(); d.onclick = 5; return String(d.onclick); },
	windowOnerrorFn: () => { const f = function () {}; window.onerror = f; const same = window.onerror === f; window.onerror = null; return same; },
	docWriteNone: () => { const d = document.implementation.createHTMLDocument(""); d.open(); d.write(); d.close(); return d.body ? d.body.innerHTML : "nobody"; },
	docWriteNull: () => { const d = document.implementation.createHTMLDocument(""); d.open(); d.write(null, undefined); d.close(); return d.body.innerHTML; },
	domParserBadType: () => new DOMParser().parseFromString("x", "text/nope"),
	domParserNull: () => new DOMParser().parseFromString(null, "text/html").body.innerHTML,
	insertRuleUndefIdx: () => { const s = document.createElement("style"); document.head.appendChild(s); return s.sheet.insertRule("a{}", undefined); },
	insertRuleStrIdx: () => { const s = document.createElement("style"); document.head.appendChild(s); s.sheet.insertRule("a{}"); return s.sheet.insertRule("b{}", "1"); },
	insertRuleBad: () => { const s = document.createElement("style"); document.head.appendChild(s); return s.sheet.insertRule("}{"); },
	replaceSyncNull: () => { const s = new CSSStyleSheet(); s.replaceSync(null); return s.cssRules.length; },
	cloneNodeUndef: () => el().cloneNode(undefined).nodeName,
	importNodeText: () => document.importNode("x"),
	adoptNodeDoc: () => document.adoptNode(document),
	createTextUndef: () => document.createTextNode(undefined).data,
	createTextNone: () => document.createTextNode(),
	createCommentNull: () => document.createComment(null).data,
	matchesPseudo: () => el().matches(undefined),
	attrValueNull: () => { const a = document.createAttribute("x"); a.value = null; return a.value; },
	setNamedItemBad: () => el().attributes.setNamedItem({}),
	getElByIdUndef: () => String(document.getElementById(undefined)),
	elementsFromPoint: () => typeof document.elementsFromPoint(1, 1).length,
	wsBadUrl: () => new WebSocket("http s://x"),
	wsNoArgs: () => new WebSocket(),
	wsCloseBad: () => { const w = new WebSocket("ws://localhost:1/"); try { w.close(1001); } finally { try { w.close(); } catch {} } },
	esNone: () => new EventSource(),
	workerNone: () => new Worker(),
	workerBadType: () => new Worker("/x.js", { type: "Module" }),
	bcNone: () => new BroadcastChannel(),
	bcNameObj: () => { const b = new BroadcastChannel({ toString() { return "n"; } }); const n = b.name; b.close(); return n; },
	audioUndef: () => new Audio(undefined).getAttribute("src"),
	audioNull: () => new Audio(null).getAttribute("src"),
	imageNoArgs: () => new Image().width,
	optionNull: () => new Option(null, null).value,
	fontFaceNone: () => new FontFace(),
	fontFaceNull: () => new FontFace("f", null).status,
	windowOrigin: () => typeof self.origin,
	docDomainNull: () => { try { document.domain = null; } catch (e) { return e.name; } return "set"; },
	perfGetEntries: () => typeof performance.getEntriesByType(undefined).length,
	perfMarkNone: () => performance.mark(),
	perfNowCall: () => typeof performance.now.call(performance),
	cacheOpenNone: () => caches.open(),
	idbOpenNone: () => indexedDB.open(),
	idbOpenBadVersion: () => indexedDB.open("x", 0),
	idbOpenVersionStr: () => { const r = indexedDB.open("x-rv1", "2"); return r.constructor.name; },
	importScriptsType: () => typeof importScripts,
};
for (const k of Object.keys(cases)) assertConsistent(k, R(cases[k]));
`;

export default [
	basicTest({
		name: "rv1-idl-edge-args",
		js: battery,
	}),
];
